# KNN

 Извлеките из данных признаки и классы.

In [12]:
import pandas
data = pandas.read_csv('wine_data.csv', names=['Class', 'Alcohol',
'Malic acid',
'Ash',
'Alcalinity of ash',
'Magnesium',
'Total phenols',
'Flavanoids',
'Nonflavanoid phenols',
'Proanthocyanins',
'Color intensity',
'Hue',
'OD280/OD315 of diluted wines',
'Proline'], header=0)
print (data)

     Class  Alcohol  Malic acid   Ash  Alcalinity of ash  Magnesium  \
0        1    13.20        1.78  2.14               11.2        100
1        1    13.16        2.36  2.67               18.6        101
2        1    14.37        1.95  2.50               16.8        113
3        1    13.24        2.59  2.87               21.0        118
4        1    14.20        1.76  2.45               15.2        112
..     ...      ...         ...   ...                ...        ...
172      3    13.71        5.65  2.45               20.5         95
173      3    13.40        3.91  2.48               23.0        102
174      3    13.27        4.28  2.26               20.0        120
175      3    13.17        2.59  2.37               20.0        120
176      3    14.13        4.10  2.74               24.5         96

     Total phenols  Flavanoids  Nonflavanoid phenols  Proanthocyanins  \
0             2.65        2.76                  0.26             1.28
1             2.80        3.24                  0.30             2.81
2             3.85        3.49                  0.24             2.18
3             2.80        2.69                  0.39             1.82
4             3.27        3.39                  0.34             1.97
..             ...         ...                   ...              ...
172           1.68        0.61                  0.52             1.06
173           1.80        0.75                  0.43             1.41
174           1.59        0.69                  0.43             1.35
175           1.65        0.68                  0.53             1.46
176           2.05        0.76                  0.56             1.35

     Color intensity   Hue  OD280/OD315 of diluted wines  Proline
0               4.38  1.05                          3.40     1050
1               5.68  1.03                          3.17     1185
2               7.80  0.86                          3.45     1480
3               4.32  1.04                          2.93      735
4               6.75  1.05                          2.85     1450
..               ...   ...                           ...      ...
172             7.70  0.64                          1.74      740
173             7.30  0.70                          1.56      750
174            10.20  0.59                          1.56      835
175             9.30  0.60                          1.62      840
176             9.20  0.61                          1.60      560

[177 rows x 14 columns]

In [15]:
data.head(200)

,Class,Alcohol,Malic acid,Ash,Alcalinity of ash,Magnesium,Total phenols,Flavanoids,Nonflavanoid phenols,Proanthocyanins,Color intensity,Hue,OD280/OD315 of diluted wines,Proline
0,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
1,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
2,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
3,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735
4,1,14.20,1.76,2.45,15.2,112,3.27,3.39,0.34,1.97,6.75,1.05,2.85,1450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
172,3,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740
173,3,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750
174,3,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835
175,3,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840
176,3,14.13,4.10,2.74,24.5,96,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560

In [34]:
target = data.Class

In [35]:
model = data.drop(['Class'], axis=1)

Оценку качества необходимо провести методом кросс-валидации по 5 блокам (5-fold). Создайте генератор разбиений, который перемешивает выборку перед формированием блоков (shuffle=True). Для воспроизводимости результата, создавайте генератор KFold с фиксированным параметром random_state=42. В качестве меры качества используйте долю верных ответов (accuracy).

In [36]:
import pandas
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import scale
from sklearn.neighbors import KNeighborsClassifier

In [37]:
import sklearn

In [38]:
kf = sklearn.model_selection.KFold(n_splits=5, shuffle=True, random_state=42)

Вычислить качество на всех разбиениях можно при помощи функции sklearn.model_selection.cross_val_score. В качестве параметра estimator передается классификатор, в качестве параметра cv — генератор разбиений с предыдущего шага. С помощью параметра scoring можно задавать меру качества, по умолчанию в задачах классификации используется доля верных ответов (accuracy). Результатом является массив, значения которого нужно усреднить.

Найдите точность классификации на кросс-валидации для метода k ближайших соседей (sklearn.neighbors.KNeighborsClassifier), при k от 1 до 50. При каком k получилось оптимальное качество? Чему оно равно (число в интервале от 0 до 1)? Данные результаты и будут ответами на вопросы 1 и 2.

In [41]:
validationTest={}
for k in range(1, 51):
    classifier = KNeighborsClassifier(n_neighbors = k)
    score = sklearn.model_selection.cross_val_score(classifier,       #классификатор
                                            model, #обучающая выборка 
                                            target, #ответы
                                            cv = kf) #генератор разбиений
    validationTest[k] = score.mean() #усредняем массив

In [43]:
optimal_k = sorted(validationTest, key = validationTest.get, reverse = True)[0]
print('optimal k: (', optimal_k, ', %.4f' %validationTest[k], ')')

optimal k: ( 1 , 0.7010 )